[tool]
name = "Polkadot.js Apps Wallet"
description = "A wallet built on the polkadot-js stack."
repository = "https://github.com/polkadot-js/apps"
homepage = "https://polkadot.js.org/apps/#/accounts"
version = "0.92"
authors = "Jaco Greeff <jacogr@gmail.com>"
documentation = "https://polkadot.js.org/docs/"
readme = "https://raw.githubusercontent.com/polkadot-js/apps/master/README.md"
license = "APACHE-2.0"
icon = "https://polkadot.js.org/logo.svg"
