[tool]
name = "Substrate Playground"
description = "Web based IDE for developing with Substrate."
repository = "https://github.com/paritytech/substrate-playground"
homepage = "https://playground.substrate.dev/"
version = "v0.5.1"
authors = ""
documentation = "https://paritytech.github.io/substrate-playground/docs/"
readme = "https://raw.githubusercontent.com/paritytech/substrate-playground/develop/README.md"
license = ""
icon = ""
