[tool]
name = "Substrate Node Template"
description = "A fresh FRAME-based node, ready for hacking."
repository = "https://github.com/substrate-developer-hub/substrate-node-template"
homepage = "https://substrate.dev"
version = "v3.0.0"
authors = "Substrate DevHub <https://github.com/substrate-developer-hub>"
documentation = "https://substrate.dev/docs/en/"
readme = "https://raw.githubusercontent.com/substrate-developer-hub/substrate-node-template/master/README.md"
license = "Unlicense"
icon = "https://substrate.dev/img/Substrate-logo.svg"
