[tool]
name = "Substrate Frontend Template"
description = "A Polkadot.js API + React based template for building Substrate Frontends."
repository = "https://github.com/substrate-developer-hub/substrate-front-end-template"
homepage = "https://substrate.dev/substrate-front-end-template/"
version = "v3.0.0"
authors = "Substrate DevHub <https://github.com/substrate-developer-hub>"
documentation = "https://substrate.dev/docs/en/"
readme = "https://raw.githubusercontent.com/substrate-developer-hub/substrate-front-end-template/master/README.md"
license = "Unlicense"
icon = "https://substrate.dev/img/Substrate-logo.svg"
