[tool]
name = "Subscan"
description = "Substrate based blockchain explorer."
repository = "https://github.com/itering/subscan-essentials"
homepage = "https://www.subscan.io"
version = ""
authors = ""
documentation = ""
readme = "https://raw.githubusercontent.com/itering/subscan-essentials/master/README.md"
license = "GPL-3.0"
icon = ""
